In [ ]:
import os
import json
import pandas as pd
import pymysql
from sqlalchemy import create_engine
import requests
import plotly.express as px
def states_correction(dataframe):
    dataframe["States"] = dataframe["States"].str.replace("andaman-&-nicobar-islands", "Andaman & Nicobar")
    dataframe["States"] = dataframe["States"].str.replace("-", " ")
    dataframe["States"] = dataframe["States"].str.title()
    dataframe["States"] = dataframe["States"].str.replace("Dadra & Nagar Haveli & Daman & Diu",
                                                        "Dadra and Nagar Haveli and Daman and Diu")

    return dataframe
# Aggregated transaction
path1= "D:/Phonepe Pulse/pulse/data/aggregated/transaction/country/india/state"

agg_trans_list = os.listdir(path1)

clm1={'States':[], 'Year':[],'Quater':[],'Transacion_type':[], 'Transacion_count':[], 'Transacion_amount':[]}


for state in agg_trans_list:
    cur_state = path1+state+"/"
    agg_yr = os.listdir(cur_state)

    for yr in agg_yr:
        cur_year = cur_state+yr+"/"
        agg_yr = os.listdir(cur_year)

        for file in agg_yr:
            cur_file = cur_year+file

            Data = open(cur_file, 'r')
            D = json.load(Data)
            for z in D['data']['transactionData']:
                Name = z['name']
                count = z['paymentInstruments'][0]['count']
                amount = z['paymentInstruments'][0]['amount']
                clm1['Transacion_type'].append(Name)
                clm1['Transacion_count'].append(count)
                clm1['Transacion_amount'].append(amount)
                clm1['States'].append(state)
                clm1['Year'].append(yr)
                clm1['Quater'].append(int(file.strip('.json')))


Agg_Trans=pd.DataFrame(clm1)
states_correction(Agg_Trans)
States	Year	Quater	Transacion_type	Transacion_count	Transacion_amount
0	Andaman & Nicobar	2018	1	Recharge & bill payments	4200	1.845307e+06
1	Andaman & Nicobar	2018	1	Peer-to-peer payments	1871	1.213866e+07
2	Andaman & Nicobar	2018	1	Merchant payments	298	4.525072e+05
3	Andaman & Nicobar	2018	1	Financial Services	33	1.060142e+04
4	Andaman & Nicobar	2018	1	Others	256	1.846899e+05
...	...	...	...	...	...	...
4489	West Bengal	2024	1	Merchant payments	407607197	2.732137e+11
4490	West Bengal	2024	1	Peer-to-peer payments	355646156	1.100744e+12
4491	West Bengal	2024	1	Recharge & bill payments	72216060	4.716192e+10
4492	West Bengal	2024	1	Financial Services	451008	5.307383e+08
4493	West Bengal	2024	1	Others	488166	3.750216e+08
4494 rows × 6 columns

# Aggregated user
path2 = "D:/Phonepe Pulse/pulse/data/aggregated/user/country/india/state"
agg_user_list = os.listdir(path2)
clm2={'States':[], 'Year':[],'Quater':[],'Brands':[], 'Counts':[], 'Percentage':[]}


for state in agg_user_list:
    cur_state = path2+state+"/"
    agg_yr = os.listdir(cur_state)

    for yr in agg_yr:
        cur_year = cur_state+yr+"/"
        agg_yr = os.listdir(cur_year)

        for file in agg_yr:
            cur_file = cur_year+file

            Data = open(cur_file, 'r')
            E = json.load(Data)

            try:
                for z in E['data']['usersByDevice']:
                    brand = z['brand']
                    count = z['count']
                    percentage = z["percentage"]
                    clm2['Brands'].append(brand)
                    clm2['Counts'].append(count)
                    clm2['Percentage'].append(percentage)
                    clm2['States'].append(state)
                    clm2['Year'].append(yr)
                    clm2['Quater'].append(int(file.strip('.json')))

            except:
                pass

Agg_user=pd.DataFrame(clm2)
states_correction(Agg_user)
States	Year	Quater	Brands	Counts	Percentage
0	Andaman & Nicobar	2018	1	Xiaomi	1665	0.247033
1	Andaman & Nicobar	2018	1	Samsung	1445	0.214392
2	Andaman & Nicobar	2018	1	Vivo	982	0.145697
3	Andaman & Nicobar	2018	1	Oppo	501	0.074332
4	Andaman & Nicobar	2018	1	OnePlus	332	0.049258
...	...	...	...	...	...	...
6727	West Bengal	2022	1	Lenovo	330017	0.015056
6728	West Bengal	2022	1	Infinix	284678	0.012987
6729	West Bengal	2022	1	Asus	280347	0.012790
6730	West Bengal	2022	1	Apple	277752	0.012671
6731	West Bengal	2022	1	Others	2196334	0.100199
6732 rows × 6 columns

# map transaction
path3 = "D:/Phonepe Pulse/pulse/data/map/transaction/hover/country/india/state"
map_trans_list = os.listdir(path3)

clm3={"States":[], "Years":[], "Quarter":[],"District":[], "Transaction_count":[],"Transaction_amount":[]}


for state in map_trans_list:
    cur_state = path3+state+"/"
    agg_yr = os.listdir(cur_state)

    for yr in agg_yr:
        cur_year = cur_state+yr+"/"
        agg_yr = os.listdir(cur_year)

        for file in agg_yr:
            cur_file = cur_year+file

            Data = open(cur_file, 'r')
            E = json.load(Data)
            for i in E['data']["hoverDataList"]:
                name = i["name"]
                count = i["metric"][0]["count"]
                amount = i["metric"][0]["amount"]
                clm3["District"].append(name)
                clm3["Transaction_count"].append(count)
                clm3["Transaction_amount"].append(amount)
                clm3["States"].append(state)
                clm3["Years"].append(yr)
                clm3["Quarter"].append(int(file.strip(".json")))

map_trans = pd.DataFrame(clm3)
states_correction(map_trans)
States	Years	Quarter	District	Transaction_count	Transaction_amount
0	Andaman & Nicobar	2018	1	north and middle andaman district	442	9.316631e+05
1	Andaman & Nicobar	2018	1	south andaman district	5688	1.256025e+07
2	Andaman & Nicobar	2018	1	nicobars district	528	1.139849e+06
3	Andaman & Nicobar	2018	2	north and middle andaman district	825	1.317863e+06
4	Andaman & Nicobar	2018	2	south andaman district	9395	2.394824e+07
...	...	...	...	...	...	...
18291	West Bengal	2024	1	nadia district	42154481	7.903014e+10
18292	West Bengal	2024	1	birbhum district	24812300	4.640025e+10
18293	West Bengal	2024	1	purba medinipur district	46212626	9.237355e+10
18294	West Bengal	2024	1	maldah district	42299563	7.671603e+10
18295	West Bengal	2024	1	darjiling district	18129044	2.927784e+10
18296 rows × 6 columns

# map user
path4= "D:/Phonepe Pulse/pulse/data/map/user/hover/country/india/state"


map_user_list = os.listdir(path4)

clm4={"States":[], "Years":[], "Quarter":[], "Districts":[], "RegisteredUser":[], "AppOpens":[]}


for state in map_user_list:
    cur_state = path4+state+"/"
    agg_yr = os.listdir(cur_state)

    for yr in agg_yr:
        cur_year = cur_state+yr+"/"
        agg_yr = os.listdir(cur_year)

        for file in agg_yr:
            cur_file = cur_year+file

            Data = open(cur_file, 'r')
            E = json.load(Data)

            for i in E["data"]["hoverData"].items():
                district = i[0]
                registered_user = i[1]["registeredUsers"]
                app_opens = i[1]["appOpens"]
                clm4["Districts"].append(district)
                clm4["RegisteredUser"].append(registered_user)
                clm4["AppOpens"].append(app_opens)
                clm4["States"].append(state)
                clm4["Years"].append(yr)
                clm4["Quarter"].append(int(file.strip(".json")))

map_user = pd.DataFrame(clm4)
states_correction(map_user)
States	Years	Quarter	Districts	RegisteredUser	AppOpens
0	Andaman & Nicobar	2018	1	north and middle andaman district	632	0
1	Andaman & Nicobar	2018	1	south andaman district	5846	0
2	Andaman & Nicobar	2018	1	nicobars district	262	0
3	Andaman & Nicobar	2018	2	north and middle andaman district	911	0
4	Andaman & Nicobar	2018	2	south andaman district	8143	0
...	...	...	...	...	...	...
18295	West Bengal	2024	1	nadia district	1671140	13679202
18296	West Bengal	2024	1	birbhum district	1056537	30502875
18297	West Bengal	2024	1	purba medinipur district	1655920	18688405
18298	West Bengal	2024	1	maldah district	1183956	33270738
18299	West Bengal	2024	1	darjiling district	686254	31485682
18300 rows × 6 columns

# top transaction
path5= "C:/Users/LENOVO/Desktop/Guvi/Project/Phonepe/pulse/data/top/transaction/country/india/state/"

top_trans_list = os.listdir(path5)


clm5={"States":[], "Years":[], "Quarter":[], "Pincodes":[], "Transaction_count":[], "Transaction_amount":[]}


for state in top_trans_list:
    cur_state = path5+state+"/"
    agg_yr = os.listdir(cur_state)

    for yr in agg_yr:
        cur_year = cur_state+yr+"/"
        agg_yr = os.listdir(cur_year)

        for file in agg_yr:
            cur_file = cur_year+file

            Data = open(cur_file, 'r')
            E = json.load(Data)

            for i in E["data"]["pincodes"]:
                entityName = i["entityName"]
                count = i["metric"]["count"]
                amount = i["metric"]["amount"]
                clm5["Pincodes"].append(entityName)
                clm5["Transaction_count"].append(count)
                clm5["Transaction_amount"].append(amount)
                clm5["States"].append(state)
                clm5["Years"].append(yr)
                clm5["Quarter"].append(int(file.strip(".json")))

top_trans = pd.DataFrame(clm5)
states_correction(top_trans)
States	Years	Quarter	Pincodes	Transaction_count	Transaction_amount
0	Andaman & Nicobar	2018	1	744101	1622	2.769298e+06
1	Andaman & Nicobar	2018	1	744103	1223	2.238042e+06
2	Andaman & Nicobar	2018	1	744102	969	3.519060e+06
3	Andaman & Nicobar	2018	1	744105	685	1.298561e+06
4	Andaman & Nicobar	2018	1	744104	340	1.039715e+06
...	...	...	...	...	...	...
8919	West Bengal	2024	1	732125	4490229	7.014125e+09
8920	West Bengal	2024	1	700006	4358390	8.114395e+09
8921	West Bengal	2024	1	700001	4321119	8.497021e+09
8922	West Bengal	2024	1	732201	4265219	9.908795e+09
8923	West Bengal	2024	1	742202	3985791	8.428173e+09
8924 rows × 6 columns

#top user

path6 = "C:/Users/LENOVO/Desktop/Guvi/Project/Phonepe/pulse/data/top/user/country/india/state/"
top_user_list = os.listdir(path6)



clm6={"States":[], "Years":[], "Quarter":[], "Pincodes":[], "RegisteredUser":[]}


for state in top_user_list:
    cur_state = path6+state+"/"
    agg_yr = os.listdir(cur_state)

    for yr in agg_yr:
        cur_year = cur_state+yr+"/"
        agg_yr = os.listdir(cur_year)

        for file in agg_yr:
            cur_file = cur_year+file

            Data = open(cur_file, 'r')
            E = json.load(Data)

            for i in E["data"]["pincodes"]:
                pincode = i["name"]
                registeredusers = i["registeredUsers"]
                clm6["Pincodes"].append(pincode)
                clm6["RegisteredUser"].append(registeredusers)
                clm6["States"].append(state)
                clm6["Years"].append(yr)
                clm6["Quarter"].append(int(file.strip(".json")))
top_user = pd.DataFrame(clm6)
states_correction(top_user)
States	Years	Quarter	Pincodes	RegisteredUser
0	Andaman & Nicobar	2018	1	744103	1608
1	Andaman & Nicobar	2018	1	744101	1108
2	Andaman & Nicobar	2018	1	744105	1075
3	Andaman & Nicobar	2018	1	744102	1006
4	Andaman & Nicobar	2018	1	744104	272
...	...	...	...	...	...
8920	West Bengal	2024	1	700015	131676
8921	West Bengal	2024	1	742304	127917
8922	West Bengal	2024	1	721101	127891
8923	West Bengal	2024	1	700150	123919
8924	West Bengal	2024	1	700091	122985
8925 rows × 5 columns

#sql insertion
# agg transaction table

db = pymysql.connect(
        host="localhost",
        user="root",
        password="1234"
)

mysql = "mysql+pymysql://root:1234@localhost/phonepe"
engine = create_engine(mysql)

connect = db.cursor()

connect.execute('create database if not exists phonepe')
connect.execute('use phonepe')

connect.execute('''create table if not exists aggregated_transaction(States VARCHAR(100),
                                        Years INT, Quater INT,
                                        Transaction_type VARCHAR(100), Transaction_count BIGINT,
                                        Transaction_amount BIGINT)''')


# agg user table


connect.execute('''create table if not exists aggregated_user (States varchar(100),
                                                                Years int,
                                                                Quarter int,
                                                                Brands varchar(50),
                                                                Transaction_count bigint,
                                                                Percentage float)''')




#map transaction table

connect.execute('''create table if not exists map_transaction(States varchar(100),
                                                                Years int,
                                                                Quarter int,
                                                                District varchar(100),
                                                                Transaction_count bigint,
                                                                Transaction_amount float)''')


#map user table

connect.execute('''create table if not exists map_user (States varchar(100),
                                                        Years int,
                                                        Quarter int,
                                                        District varchar(100),
                                                        RegisteredUser bigint,
                                                        AppOpens bigint)''')


# top transaction table

connect.execute('''create table if not exists top_transaction(States varchar(100),
                                                                Years int,
                                                                Quarter int,
                                                                pincode int,
                                                                Transaction_count bigint,
                                                                Transaction_amount bigint)''')





# top user table

connect.execute('''create table if not exists top_user (States varchar(100),
                                                        Years int,
                                                        Quarter int,
                                                        Pincode int,
                                                        RegisteredUser bigint
                                                        )''')

db.commit()


Agg_Trans.to_sql('aggregated_transaction',engine,if_exists='append',index=False)
Agg_user.to_sql('aggregated_user', engine, if_exists='append', index=False)
map_trans.to_sql('map_transaction',engine,if_exists='append',index=False)
map_user.to_sql('map_user', engine, if_exists='append', index=False)
top_trans.to_sql('top_transaction',engine,if_exists='append',index=False)
top_user.to_sql('top_user', engine, if_exists='append', index=False)
8925